version: '3.2'
services:
  sample:
    container_name: restaurant-app
    build:
      context: .
      dockerfile: ./compose/local/react.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
